name: Testes com PostgreSQL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Esperar o PostgreSQL subir
        run: |
          until pg_isready -h localhost -p 5432 -U test; do
            sleep 1
          done

      - name: Rodar testes
        run: |
          echo "Aqui você roda seus testes, parabéns."
